**How to create a Null Values in a data**

- None
- np.nan

In [1]:
import numpy as np
import pandas as pd

In [3]:
d={'Names':['Ramesh','Suresh',None,'Mahesh'],
   'Age':[None,22,24,25],
   'City':['Hyd','Blr','Pune',None]}
df1=pd.DataFrame(d)
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [4]:
df1.to_csv('data1.csv',index=False)

In [5]:
d={'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
   'Age':[np.nan,22,24,25],
   'City':['Hyd','Blr','Pune',np.nan]}
df2=pd.DataFrame(d)
df2

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2     NaN  24.0  Pune
3  Mahesh  25.0   NaN

In [6]:
df2.to_csv('data2.csv',index=False)

- Categorical data use **None**
- Numerical data use **np.nan**

In [8]:
df1.isnull()
#isnull = wherever Null value there it display as true

   Names    Age   City
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [9]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [11]:
df1
df1.values
df1.dtypes
df1.isnull()
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**fill the values**

In [14]:
df1.fillna(30)
# it is not good it is random fill

    Names   Age  City
0  Ramesh  30.0   Hyd
1  Suresh  22.0   Blr
2      30  24.0  Pune
3  Mahesh  25.0    30

In [18]:
# i am not doing inplace=True
df1['City'].fillna('Delhi')

0      Hyd
1      Blr
2     Pune
3    Delhi
Name: City, dtype: object

In [17]:
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [20]:
#pad,ffill,bfill,backfill
#axis=0 axis=1
df1.fillna(method='pad')
df1.fillna(method='pad',axis=1)

C:\Users\Achyutha\AppData\Local\Temp\ipykernel_23104\1394791076.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')
C:\Users\Achyutha\AppData\Local\Temp\ipykernel_23104\1394791076.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)

    Names     Age  City
0  Ramesh  Ramesh   Hyd
1  Suresh    22.0   Blr
2    None    24.0  Pune
3  Mahesh    25.0  25.0

In [21]:
df1.fillna(method='bfill')
df1.fillna(method='bfill',axis=1)

C:\Users\Achyutha\AppData\Local\Temp\ipykernel_23104\866773176.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')
C:\Users\Achyutha\AppData\Local\Temp\ipykernel_23104\866773176.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill',axis=1)

    Names   Age  City
0  Ramesh   Hyd   Hyd
1  Suresh  22.0   Blr
2    24.0  24.0  Pune
3  Mahesh  25.0  None

In [22]:
df1.fillna(method='pad')
df1.fillna(method='pad',axis=1)

C:\Users\Achyutha\AppData\Local\Temp\ipykernel_23104\1394791076.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')
C:\Users\Achyutha\AppData\Local\Temp\ipykernel_23104\1394791076.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)

    Names     Age  City
0  Ramesh  Ramesh   Hyd
1  Suresh    22.0   Blr
2    None    24.0  Pune
3  Mahesh    25.0  25.0

In [24]:
df1.values

array([['Ramesh', nan, 'Hyd'],
       ['Suresh', 22.0, 'Blr'],
       [None, 24.0, 'Pune'],
       ['Mahesh', 25.0, None]], dtype=object)

- mean
- median
- mode

In [25]:
df1['Age'].fillna(30)

0    30.0
1    22.0
2    24.0
3    25.0
Name: Age, dtype: float64

In [26]:
#instead of random value take mean of age
age_mean=df1['Age'].mean()
df1['Age'].fillna(age_mean)

0    23.666667
1    22.000000
2    24.000000
3    25.000000
Name: Age, dtype: float64

In [27]:
age_median=df1['Age'].median()
df1['Age'].fillna(age_median)

0    24.0
1    22.0
2    24.0
3    25.0
Name: Age, dtype: float64

In [28]:
# there is no particulaar rule how to fill the missing values
# it is completely based on situation

In [29]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])

In [30]:
d1

   Gender
0    Male
1  Female
2    None

In [32]:
d={'Female':0,'Male':1}
d1['Gender']=d1['Gender'].map(d)
d1

   Gender
0     1.0
1     0.0
2     NaN

In [33]:
# the student think that i want to fill a missing 
# data is numerical : mean
(1+0)/2

0.5

**situation-2**

In [34]:
# ML algorithm
# Churn:stay or not stay

In [35]:
churn=['stay','not_stay',None]
churn=[0,1,None]
churn=[0,1,0.5]

**situation-3**

In [36]:
# No of days
[20,25,np.nan,31]
(20+25+31)/3

25.333333333333332

**situation-4**

In [37]:
course=['DS','AI','DS','Devops','AI','Devlops','AI']
fee=[30000,2700,30000,22000,3000,22000,np.nan]
pd.DataFrame(zip(course,fee))

# first group by with course
# then take corresponding course values only

         0        1
0       DS  30000.0
1       AI   2700.0
2       DS  30000.0
3   Devops  22000.0
4       AI   3000.0
5  Devlops  22000.0
6       AI      NaN

**KNNImputer**

- KNN: K-nearest neighbours
- where k is a number
- instead of taking avg of all the values data 
   - we will find the neighbours who are close with missing data row
   - by using euclidian  distance calculation will identify the neighbour rows
   - suppose k=2 will identify the two closest rows
   - those closest  rows values will take it will calculate the mean
   - finaly will fill the mean

In [40]:
salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(salary,age),
             columns=['Salary','Age'])
df

    Salary  Age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

- sklearn 
  - impute
     - KNNImputer

In [44]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2)
pd.DataFrame(imputer.fit_transform(df))

         0     1
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0